### PR TITLE
Adapt for conda-build3.

### PR DESCRIPTION
**Pull request by cbrueffer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cbrueffer** [comment]
Obsoletes #3

**Comment by cbrueffer** [comment]
@bgruening ready to merge

**Comment by cbrueffer** [comment]
@bgruening one more ready

**Comment by bgruening** [comment]
Upps, sorry.

**Pull request merged**
